# See LICENSE file for copyright and license details.

before_install:
    - sudo add-apt-repository -y ppa:hansjorg/rust
    - sudo apt-get update

install:
    - sudo apt-get install rust-nightly

script:
    - make

# vim: set tabstop=4 shiftwidth=4 softtabstop=4 expandtab:
